getwd()
WHO=read.csv("WHO.csv")
etwd()
getwd
getwd()
getwd()
getwd()
getwd()
setwd("~/")
setwd(/home/jatin/Mitedx)
setwd("home/jatin/Mitedx")
setwd("~/Mitedx")
WHO=read.csv("WHO.csv")
str(WHO)
View(WHO)
View(WHO)
summary(WHO)
WHO.Europe=subset(Region=="Europe")
WHO.Europe=subset(WHO,Region=="Europe")
str(WHO.Europe)
write.csv(WHO.Europe,"WHO.Europe.csv")
ls()
rm(WHO.Europe
)
ls()
WHO$Under15
mean(WHO$Under15)
sd(WHO$Under15)
summary(WHO$Under15)
which.min(WHO$Under15)
WHO$Country[86]
which.max(WHO$Under15)
WHO$Country[124]
plot(WHO$GNI,WHO$FertilityRate)
Outliers=subset(WHO,GNI>25000&Fertility Rate>2.5)
Outliers=subset(WHO,GNI>25000&FertilityRate>2.5)
nrow(Outliers)
Outliers=subset(WHO,GNI>10000&FertilityRate>2.5)
nrow(Outliers)
Outliers[c("Country,"GNI",FertilityRate")]
Outliers[c("Country","GNI",FertilityRate")]
Outliers[c("Country","GNI",FertilityRate")]
Outliers[c("Country","GNI","FertilityRate")]
WHO$Over60
mean(WHO$Over60)
summary(WHO$Over60)
which.min(WHO$Over60)
WHO$Country[183]
whic.max(WHO$Over60)
which.max(WHO$Over60)
WHO$Country[86]
WHO$LiteracyRate
summary(WHO$LiteracyRate)
which.max(WHO$LiteracyRate)
WHO$Country[44]
hist(WHO$CellularSubscribers)
boxplot(WHO$LifeExpectancy ~WHO$Region)
boxplot(WHO$LifeExpectancy ~WHO$Region,xlab="" ylab="Life Expectancies",main="Life Expectancies According toRegions")
boxplot(WHO$LifeExpectancy ~WHO$Region,xlab="", ylab="Life Expectancies",main="Life Expectancies According toRegions")
table(WHO$Region)
tapply(WHO$Over60,WHO$Region,mean)
tapply(WHO$LiteracyRate,WHO$Region,mean)
tapply(WHO$LiteracyRate,WHO$Region,min,na.rm=TRUE)
tapply(WHO$ChildMortality,WHO$Region,min,na.rm=TRUE)
