
movies=read.table("movielens.txt",sep="|",quote="\"")
colnames(movies) = c("ID", "Title", "ReleaseDate", "VideoReleaseDate", "IMDB", "Unknown", "Action", "Adventure", "Animation", "Childrens", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "FilmNoir", "Horror", "Musical", "Mystery", "Romance", "SciFi", "Thriller", "War", "Western")
str(movies)
movies$ID=NULL
movies$ReleaseDate=NULL
movies$VideoReleaseDate=NULL
movies$IMDB=NULL
table(movies$Comedy)
table(movies$Western)
table(movies$Romance,movies$Drama)
table(movies$Romance, movies$Drama)
str(movie)
str(movies)
distances=dist(movies[2:20],method="euclidean")
clusterMovies=hclust(distances,method="ward.D")
plot(clusterMovies)
clusterGroups=cutree(clusterMovies,k=10)
tapply(movies$Action,clusterGroups,mean)
tapply(movies$Romance,clusterGroups,mean)
subset(movies,title=="Men In Black (1997)")
subset(movies,title=="Men in Black (1997)")
subset(movies,Title=="Men in Black (1997)")
clusterGroups[257]
cluster2=subset(movies,clusterGroups==2)
cluster2$Title[1:10]
clusterGroups1=cutree(clusterMovies,k=2)
tapply(movies$Action,clusterGroups,mean)
tapply(movies$Action,clusterGroups1,mean)
subset(clusterGroups1)
table(clusterGroups1)
table(clusterGroups1$2)
clusterGroups1
summary(clusterGroups1)
str(clusterGroups1)
tapply(movies$Adventure,clusterGroups1,mean)
tapply(movies$Animation,clusterGroups1,mean)
tapply(movies$Comedy,clusterGroups1,mean)
tapply(movies$Childrens,clusterGroups1,mean)
tapply(movies$Crime,clusterGroups1,mean)
tapply(movies$Documentary,clusterGroups1,mean)
tapply(movies$Drama,clusterGroups1,mean)
tapply(movies$Fantasy,clusterGroups1,mean)
tapply(movies$FilmNoir,clusterGroups1,mean)
tapply(movies$Horror,clusterGroups1,mean)
tapply(movies$Musical,clusterGroups1,mean)
tapply(movies$Mystery,clusterGroups1,mean)
tapply(movies$Romance,clusterGroups1,mean)
tapply(movies$SciFi,clusterGroups1,mean)
tapply(movies$Thriller,clusterGroups1,mean)
tapply(movies$War,clusterGroups1,mean)
tapply(movies$Western,clusterGroups1,mean)
