
trials = read.csv("clinical_trial.csv", stringsAsFactors=FALSE)

sum(nchar(trials$abstract) == 0)
which.min(nchar(trials$title))
trials$title[1258]
corpusTitle=Corpus(VectorSource(trials$title))
corpusAbstract=Corpus(VectorSource(trials$abstract))
corpusTitle = tm_map(corpusTitle, tolower)
corpusTitle = tm_map(corpusTitle, tolower)
corpusTitle = tm_map(corpusTitle, PlainTextDocument)
corpusTitle = tm_map(corpusTitle, removePunctuation)
corpusTitle = tm_map(corpusTitle, removeWords, stopwords("english"))
corpusTitle = tm_map(corpusTitle, stemDocument)
dtmTitle = DocumentTermMatrix(corpusTitle)
dtmTitle = removeSparseTerms(dtmTitle, 0.95)
dtmTitle = as.data.frame(as.matrix(dtmTitle))
corpusAbstract=tm_map(CorpusAbstract,tolower)
corpusAbstract=tm_map(corpusAbstract,tolower)
corpusAbstract=tm_map(corpusAbstract,removePunctuation)
corpusAbstract=tm_map(corpusAbstract,PlainTextDocument)
corpusAbstract=tm_map(corpusAbstract,removeWords,stopwords("english"))
corpusAbstract=tm_map(corpusAbstract,stemDocument)
dtmAbstract=removeSparseTerms(corpusAbstract,0.95)
dtmAbstract=DocumentTermMatrix(corpusAbstract)
dtmAbstract=removeSparseTerms(dtmAbstract,0.95)
dtmAbstract=as.data.frame(as.data.matrix(dtmAbstract))
dtmAbstract=as.data.frame(as.matrix(dtmAbstract))
dtmAbstract
str(dtmAbstract)
colnames(dtmAbstract)=paste0("A",colnames(dtmAbstract))
colnames(dtmTitle)=paste0("T",colnames(dtmTitle))
dt=cbind(dtmTitle,dtmAbstract)
colnames(dtmTitle) = paste0("T", colnames(dtmTitle))
colnames(dtmAbstract) = paste0("A", colnames(dtmAbstract))
dtm = cbind(dtmTitle, dtmAbstract)
dtm$trial=clinic$trial
ncol(dtm)
set.seed(144)
library(caTools)
split=set.sample.split(dtm,splitRatio=0.7)
split=sample.split(dtm$trial,splitRatio=0.7)
split=sample.split(dtm$trial,0.7)
train=subset(dtm,split==TRUE)
test=subset(dtm,split==FALSE)
table(test,dtm$trial)
table(train$trial)
library(rpart)
library(rpart.plot)
trialcart=rpart(trial~.,data=train,method="class")
prp(trialcart)
prediction=predict(trialcart,newdata=test,method="class")
predictiontrain=predict(trialcart,newdata=train,method="class")
predictiontrain=predict(trialcart,newdata=train,type ="class")
table(train$trial,predictiontrain)
(631 +441)/(631 +441 +131 +99)
predTrain = predict(trialCart)[,2]
predTrain = predict(trialcart)[,2]
summary(predTrain)
summary(traincart)
summary(trialcart)
table(train$trial, predTrain >= 0.5)
senstivity=(441)/(441+131)
specificity=(631)/(631+99)
specificity
predictTest[,2]
predTest=predictTest[,2]
predictTest[]
prediction=predict(trialcart,newdata=test,method="class")[,2]
table(test$trial,prediction>=0.5)
libraru(ROCR)
library(ROCR)
pred=prediction(prediction,test$trial)
as.numeric(performance(pred,"auc")@y.values)
