x=c(6.5,7.0,7.5, 8.0,8.5)
avg(x)
mean(x)
setwd("~/Mitedx/LinearRegression")
wine=read.csv("wine.csv")
str(wine)
model1=lm(Price~AGST,data=wine)
summary(model1)
SSE=sum(model1$residuals^2)
SSE
model2=lm(Price~AGST+HarvestRain,data=wine)
model2
summary(model2)
SSE=sum(model2$residuals^2)
SSE
model2=lm(Price~AGST+HarvestRain+Age+FrancePop+WinterRain+Year,data=wine)
summary(model2)
SSE=sum(model2$residuals^2)
SSE
model3=lm(Price~HarvestRain+WinterRain,data=wine)
summary(model3)
model4=lm(Price~HarvestRain+AGST+WinterRain,data=wine)
summary(model4)
cor(wine$WinterRain,wine$Price)
cor(wine$Age,wine$FrancePop)
cor(wine)
model5=lm(Price~HarvestRain+WinterRain+Age+AGST,data=wine)
summary(model5)
wine_test=read.csv("wine_test.csv")
predictTest=predict(model5,newdata = wine_test)
predictTest$price
predictTest
model5$price
str(wine_test)
SSE=sum((wine_test$Price-predictTest)^2)
SST=sum((wine_test$Price-mean(wine$Price))^2)
R=1-SSE/SST
R
