setwd("~/Mitedx/Second assignment")
cps=read.csv(C"CPSData.csv
")
cps=read.csv("CPSData.csv
")
cps=read.csv("CPSData.csv")
str(cps)
table(cps$Region,is.na(cps$MetroAreaCode))
tapply(cps$Region,cps$MetroAreaCode,mean
)
tapply(cps$Region,cps$MetroAreaCode,mean
,na.rm=TRUE)
tapply(cps$Region,is.na(cps$MetroAreaCode),mean
,na.rm=TRUE)
tapply(is.na(CPS$MetroAreaCode), CPS$State, mean)
tapply(is.na(cps$MetroAreaCode), cps$State, mean)
sort(tapply(is.na(cps$MetroAreaCode), cps$State, mean))
mac=read.csv("MetroAreaCodes.csv
")
mac=read.csv("MetroAreaCodes")
mac=read.csv("MetroAreaCodes.csv")
str(mac)
cc=read.csv("CountryCode.csv")
cc=read.csv("CountryCodes.csv")
str(cc)
cps=merge(cps,mac by.x="MetroAreaCode",by.y="Code",all.x=TRUE)
cps=merge(cps,MetroAreaMap by.x="MetroAreaCode",by.y="Code",all.x=TRUE)
cps=merge(cps,MetroAreaMap,by.x="MetroAreaCode",by.y="Code",all.x=TRUE)
cps=merge(cps,mac,by.x="MetroAreaCode",by.y="Code",all.x=TRUE)
str(cps)
table(cps$MetroAreaCode)
summary(cps$MetroAreaCode)
summary(cps$MetroArea)
table(cps$MetroArea)
sort(table(cps$MetroArea))
tapply(cps$Hispanic,cps$MetroArea,mean)
sort(tapply(cps$Hispanic,cps$MetroArea,mean))
tasian=subset(cps,cps$Hispanic=="ASIAN")
tasian
summary(tasian)
table(cps$Hispanic="Asian")
table(cps$Hispanic=="Asian")
tasian=subset(cps,cps$Hispanic=="Asian")
tasian1=subset(cps,cps$Hispanic=="Asian")
tasian1=subset(cps,Hispanic=="Asian")
str(tasian1)
tasian1=subset(cps,cps$Race=="Asian")
tapply(cps$Race=="Asian",cps$MetroArea,mean)
sort(tapply(cps$Race=="Asian",cps$MetroArea,mean))
sort(tapply(cps$Race=="Asian",cps$MetroArea,mean,na.rm=TRUE))
View(cc)
View(cc)
cps=merge(cps,cc,by.x="Country",by.y="Code",all.x=TRUE)
View(cps)
View(cps)
cps=merge(cps,cc,by.x="Code",by.y="Country",all.x=TRUE)
CPS = merge(CPS, CountryMap, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
cps = merge(cps, cc, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
str(cps)
summary(cps)
summary(cps$CountryOfBirthCode)
summary(cps$Country)
tapply(cps$Country=="India",cps$MetroArea,mean,na.rm=TRUE)
sort(tapply(cps$Country=="India",cps$MetroArea,mean,na.rm=TRUE))
sort(tapply(cps$Country=="Brazil",cps$MetroArea,mean,na.rm=TRUE))
