load("~/Mitedx/LinearRegression/ClimateChange/.RData")
setwd("~/AnalyticsEdge-edx/Clustering/Image Segmentation")
flower=read.csv("flower.csv")
flower=read.csv("flower.csv",header=FALSE)
str(flower)
flowermatrix=as.matrix(flower)
str(flowermatrix)
flowerVector=as.vector(flowermatrix)
str(flowerVector)
floweVector2=as.vector(flower)
str(floweVector2)
distance=dist(flowerVector,method="euclidean")
clusterIntensity=hclust(distance,method="ward.D")
plot(clusterIntensity)
rect.hclust(clusterIntensity,k=3,border="red")
flowerclusters=cutree(clusterIntensity,k=3)
flowerclusters
tapply(flowerVector,flowerclusters,mean)
dim(flowerclusters)=c(50,50)
image(flowerclusters,axis=FALSE)
image(flowermatrix,axes=FALSE,col=grey(seq(0,1,length=256)))
use warnings()
warnings()
