

load("~/Mitedx/LinearRegression/ClimateChange/.RData")
setwd("~/AnalyticsEdge-edx/TextAnalytics/Assignment/spam email")
email=read.csv("emails.csv")
email
str(email)
ncol(email$spam)
email$spam
table(email$spam)
email$text[[1]]
max(nchar(email$text))
nchar(email$text)
max(nchar(email$text))
email=read.csv("emails.csv",stringsAsFactors = )
email=read.csv("emails.csv",stringsAsFactors = FALSE)
max(nchar(email$text))
min(nchar(email$text))
which.min(nchar(email$text))
library(tm)
library(SnowballC)
corpus=Corpus(VectorSource(email$text))
corpus=tm_mao
corpus=tm_map(corpus,tolower)
corpus=tm_map(corpus,removePunctuation)
corpus=tm_map(corpus,PlainTextDocument)
corpus=tm_map(corpus,removeWords,stopwords("english"))
corpus=tm_map(corpus,stemDocument)
dtm=DocumentTermMatrix(corpus)
dtm
spdtm=removeSparseTerms(dtm,0.95)
spdtm
emailsparse=as.data.frame(as.matrix(spdtm))
colSums(emailsparse)
which.max(colSums(emailsparse))
emailsparse$spam=email$spam
which(colsums(emailsparse$text)==5000)
which(colSums(emailsparse$text)==5000)
which(colSums(emailsparse)==5000)
colSums(emailsparse)
x=colSums(emailsparse)
which(x>=5000)
x=colSums(emailsparse$text)
sort(colSums(subset(emailsSparse, spam == 0))).
sort(colSums(subset(emailsparse, spam == 0))).
sort(colSums(subset(emailsparse, spam == 0)))
which(emailsparse$spam>=1000)
which(colSums(emailsparse$spam>=1000))
which(colSums(emailsparse,spam>=1000))
emailsparse$spam
colSums(emailsparse,spam)
colSums(emailsparse)
sort(colSums(emailsparse,spam==1))
sort(colSums(subset(emailsparse,spam==1)))
emailsparse$spam=as.factor(emailsparse$spam)
set.seed(123)
split=sample.split(emailsparse,0.7)
library(caTools)
split=sample.split(emailsparse,0.7)
split=sample.split(emailsparse$spam,0.7)
train=subset(emailsparse,SplitRatio==TRUE)
train=subset(emailsparse,split==TRUE)
test=subset(emailsparse,split==FALSE)
library(rpart)
library(rpart.plot)
spamCART=rpart(spam~,data=train,method="class")
spamCART=rpart(spam~.,data=train,method="class")
spamLOG=glm(spam~.,data=train,family="bionomial'")
spamLOG=glm(spam~.,data=train,family="bionomial")
spamLOG=glm(spam~.,data=train,family="binomial")
spamRF=randomForest(spam~.,data=train)
library(ROCR)
spamRF=randomForest(spam~.,data=train)
library(ROC)
install.packages("randomForest")
library(randomForest)
spamRF=randomForest(spam~.,data=train)
spamRF=randomForest(spam~.,data=train)
set.seed(123)
spamRF=randomForest(spam~.,data=train)
spamF=randomForest(spam~.,data=train)
names(spam) <- make.names(names(spam))
names(train) <- make.names(names(train))
train
spamRF=randomForest(spam~.,data=train)
predTrainCART=predict(spamCART)[,2]
predTrainCART
predTrainLog=predict(spamLOG,type="response")
predTrainRF=predict(spamRF,type="prob")[,2]
table(predTrainLog < 0.00001)
table(predTrainLog > 0.99999)
table(predTrainLog >= 0.00001 & predTrainLog <= 0.99999)
summary(spamLOG)
prp(spamCART)
table(train$spam,predTrainLog>0.5)
(2941+942)/(2941+942+111+16)
predictionTrainLog = prediction(predTrainLog, train$spam)
as.numeric(performance(predictionTrainLog, "auc")@y.values)
predictionSpamCart=prediction(predTrainCART,train$spam,type="class")
table(train$spam, predTrainCART > 0.5)
(2884+887)/nrow(train)
as.numeric(performance(predictionTrainCART, "auc")@y.values)
predictionTrainCART = prediction(predTrainCART, train$spam)
as.numeric(performance(predictionTrainCART, "auc")@y.values)
table(train$spam, predTrainRF >0.5)
predictionTrainRF = prediction(predTrainRF, train$spam)
as.numeric(performance(predictionTrainRF, "auc")@y.values)
(3016 +912)/nrow(train)
predTestLog = predict(spamLog, newdata=test, type="response")
predTestLog = predict(spamLOG, newdata=test, type="response")
predTestCART = predict(spamCART, newdata=test)[,2]
predTestRF = predict(spamRF, newdata=test, type="prob")[,2]
names(train) <- make.names(names(train))
predTestRF = predict(spamRF, newdata=test, type="prob")[,2]
table(test$spam, predTestLog > 0.5)
(1207+389)/nrow(test)
predictionTestLog = prediction(predTestLog, test$spam)
as.numeric(performance(predictionTestLog, "auc")@y.values)
table(test$spam,predTestCART>0.5)
(1232+378)/nrow(test)
predictionTestCart=prediction(predTestCART,test$spam)
as.numeric(as.performance(predictionTestCart,"auc")@y.values)
as.numeric(performance(predictionTestCart,"auc")@y.values)
table(test$spam,predTestRF>0.5)
predTestRF = predict(spamRF, newdata=test, type="prob")[,2]
